apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-assets-pvc
  namespace: app-launcher
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
