apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-conf-pv
  namespace: app-launcher
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /opt/cnsd-tools/nginx
    server: 10.9.9.23

