apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-assets-nfs
  namespace: app-launcher
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: static-assets-pvc
    namespace: app-launcher
  nfs:
    path: /opt/cnsd-tools/assets
    server: 10.9.9.23
